'use strict';

const path = require('path');
const os = require('os');
const { getProfile, seenJobBefore, saveTailored, markDelivered } = require('./db');
const { tailorResume, calculateAtsScore, improveResume, createJobTrace } = require('./llm');
const { renderResumeDocx } = require('./renderDocx');
const { sendResumeEmail } = require('./mailer');

const ATS_IMPROVEMENT_THRESHOLD = 95;

async function processJob(job, userId = 'me') {
  const alreadySeen = await seenJobBefore(job, userId);
  if (alreadySeen) return { skipped: true };

  if (!job.jd_text || job.jd_text.trim().length < 50) {
    console.log(`· Skipping ${job.job_id} — no JD`);
    return { skipped: true };
  }

  const trace = createJobTrace(job);
  const profile = await getProfile(userId);

  // First tailoring pass
  let resume = await tailorResume(profile, job, trace);
  let ats = await calculateAtsScore(resume, job, trace);
  let improved = false;

  console.log(`✓ ATS Score for ${job.company}: ${ats.score}/100`);

  // Improvement iteration if score < threshold
  if (ats.score < ATS_IMPROVEMENT_THRESHOLD) {
    console.log(`↑ Score ${ats.score} < ${ATS_IMPROVEMENT_THRESHOLD} — running improvement pass...`);
    try {
      const improvedResume = await improveResume(resume, job, ats, trace);
      const improvedAts = await calculateAtsScore(improvedResume, job, trace);
      console.log(`✓ Improved ATS: ${improvedAts.score}/100`);
      // Use improved version only if it's actually better
      if (improvedAts.score > ats.score) {
        resume = improvedResume;
        ats = improvedAts;
        improved = true;
      }
    } catch (e) {
      console.error('Improvement pass failed:', e.message);
    }
  }

  const safe = (s) => String(s || 'x').replace(/[^a-z0-9]+/gi, '_');
  const fileName = `resume_${safe(job.company)}_${safe(job.title)}.docx`;
  const filePath = path.join(os.tmpdir(), fileName);
  await renderResumeDocx(resume, filePath);

  const tailoredId = await saveTailored(job.job_id, resume, filePath, userId);

  await sendResumeEmail({
    subject: `[ATS ${ats.score}/100] ${job.title} @ ${job.company}`,
    text: buildEmailBody({ job, ats, improved }),
    attachmentPath: filePath,
    attachmentName: fileName,
  });

  await markDelivered(tailoredId, job.job_id, { ...ats, improved });

  trace.update({ output: { ats_score: ats.score, improved, resume_file: fileName } });

  return { skipped: false, filePath, tailoredId, atsScore: ats.score, improved };
}

function buildEmailBody({ job, ats, improved }) {
  return `
RESUME ASSISTANT — TAILORED RESUME
====================================

Role:     ${job.title}
Company:  ${job.company}
${job.url ? `Job URL:  ${job.url}` : ''}

ATS MATCH SCORE: ${ats.score}/100 ${improved ? '(improved)' : ''}
${ats.summary}

✅ Matched Keywords:
${(ats.matched_keywords || []).map((k) => `  • ${k}`).join('\n')}

⚠️  Missing Keywords:
${(ats.missing_keywords || []).map((k) => `  • ${k}`).join('\n')}

====================================
Tailored resume attached as .docx
Generated by Resume Assistant
  `.trim();
}

module.exports = { processJob };
