'use strict';

const path = require('path');
const os = require('os');
const { getProfile, seenJobBefore, saveTailored, markDelivered } = require('./db');
const { tailorResume, calculateAtsScore, improveResume, createJobTrace } = require('./llm');
const { renderResumeDocx } = require('./renderDocx');
const { sendResumeEmail } = require('./mailer');

const ATS_IMPROVEMENT_THRESHOLD = 95;

async function processJob(job, userId = 'me') {
  const alreadySeen = await seenJobBefore(job, userId);
  if (alreadySeen) return { skipped: true };

  if (!job.jd_text || job.jd_text.trim().length < 50) {
    console.log(`· Skipping ${job.job_id} — no JD`);
    return { skipped: true };
  }

  const trace = createJobTrace(job);
  const profile = await getProfile(userId);

  // First tailoring pass
  let resume = await tailorResume(profile, job, trace);
  let ats = await calculateAtsScore(resume, job, trace);
  let improved = false;
  let substitutions = [];

  console.log(`✓ ATS Score for ${job.company}: ${ats.score}/100`);

  // Improvement iteration if score < threshold
  if (ats.score < ATS_IMPROVEMENT_THRESHOLD) {
    console.log(`↑ Score ${ats.score} < ${ATS_IMPROVEMENT_THRESHOLD} — running improvement pass...`);
    try {
      const improveResult = await improveResume(resume, job, ats, trace);
      const improvedResume = improveResult.resume || improveResult;
      substitutions = improveResult.substitutions || [];
      const improvedAts = await calculateAtsScore(improvedResume, job, trace);
      console.log(`✓ Improved ATS: ${improvedAts.score}/100`);
      if (substitutions.length) {
        console.log(`↳ ${substitutions.length} synonym substitution(s):`);
        substitutions.forEach(s => console.log(`  "${s.original_phrase}" → "${s.new_phrase}" (JD: ${s.jd_keyword})`));
      }
      // Use improved version only if it's actually better
      if (improvedAts.score > ats.score) {
        resume = improvedResume;
        ats = improvedAts;
        improved = true;
      } else {
        substitutions = [];
      }
    } catch (e) {
      console.error('Improvement pass failed:', e.message);
    }
  }

  const safe = (s) => String(s || 'x').replace(/[^a-z0-9]+/gi, '_');
  const fileName = `resume_${safe(job.company)}_${safe(job.title)}.docx`;
  const filePath = path.join(os.tmpdir(), fileName);
  await renderResumeDocx(resume, filePath);

  const tailoredId = await saveTailored(job.job_id, resume, filePath, userId);
  await markDelivered(tailoredId, job.job_id, { ...ats, improved, substitutions });

  try {
    await sendResumeEmail({
      subject: `[ATS ${ats.score}/100] ${job.title} @ ${job.company}`,
      text: buildEmailBody({ job, ats, improved, substitutions }),
      attachmentPath: filePath,
      attachmentName: fileName,
    });
  } catch (e) {
    console.error(`⚠ Email failed for ${job.job_id} (resume still saved):`, e.message);
  }

  trace.update({ output: { ats_score: ats.score, improved, substitutions_count: substitutions.length, resume_file: fileName } });

  return { skipped: false, filePath, tailoredId, atsScore: ats.score, improved, substitutions };
}

function buildEmailBody({ job, ats, improved, substitutions }) {
  let body = `
RESUME ASSISTANT — TAILORED RESUME
====================================

Role:     ${job.title}
Company:  ${job.company}
${job.url ? `Job URL:  ${job.url}` : ''}

ATS MATCH SCORE: ${ats.score}/100 ${improved ? '(improved)' : ''}
${ats.summary}

✅ Matched Keywords:
${(ats.matched_keywords || []).map((k) => `  • ${k}`).join('\n')}

⚠️  Missing Keywords:
${(ats.missing_keywords || []).map((k) => `  • ${k}`).join('\n')}`;

  if (substitutions && substitutions.length > 0) {
    body += `\n\n🔄 Synonym Substitutions Applied:
${substitutions.map((s) => `  • "${s.original_phrase}" → "${s.new_phrase}"\n    (JD keyword: ${s.jd_keyword})`).join('\n')}

These substitutions use JD terminology where your existing
experience is semantically equivalent. No new facts were added.`;
  }

  body += `\n\n====================================
Tailored resume attached as .docx
Generated by Resume Assistant`;

  return body.trim();
}

module.exports = { processJob };
