'use strict';

const path = require('path');
const os = require('os');
const { getProfile, seenJobBefore, saveTailored, markDelivered } = require('./db');
const { tailorResume, calculateAtsScore } = require('./llm');
const { renderResumeDocx } = require('./renderDocx');
const { sendResumeEmail } = require('./mailer');
const { scrapeJobsFromEmail } = require('./scraper');

async function processJob(job) {
  const alreadySeen = await seenJobBefore(job);
  if (alreadySeen) return { skipped: true };

  let jobToProcess = { ...job };

  // Try to scrape full JD from LinkedIn URLs in the email
  const scraped = await scrapeJobsFromEmail(
    job.emailText || '',
    job.jobUrls || [],
    job.title,
    job.company
  );

  if (scraped && scraped.length > 0) {
    jobToProcess = {
      ...jobToProcess,
      title: scraped[0].title || job.title,
      company: scraped[0].company || job.company,
      jd_text: scraped[0].jd_text,
      url: scraped[0].url,
    };
    console.log(`✓ Scraped full JD for ${jobToProcess.company} — ${jobToProcess.jd_text.length} chars`);
  }

  const profile = await getProfile();
  const resume = await tailorResume(profile, jobToProcess);
  const ats = await calculateAtsScore(resume, jobToProcess);

  console.log(`✓ ATS Score for ${jobToProcess.company}: ${ats.score}/100`);

  const safe = (s) => String(s || 'x').replace(/[^a-z0-9]+/gi, '_');
  const fileName = `resume_${safe(jobToProcess.company)}_${safe(jobToProcess.title)}.docx`;
  const filePath = path.join(os.tmpdir(), fileName);
  await renderResumeDocx(resume, filePath);

  const tailoredId = await saveTailored(job.job_id, resume, filePath);

  await sendResumeEmail({
    subject: `[ATS ${ats.score}/100] ${jobToProcess.title} @ ${jobToProcess.company}`,
    text: buildEmailBody({ job: jobToProcess, ats }),
    attachmentPath: filePath,
    attachmentName: fileName,
  });

  await markDelivered(tailoredId);
  return { skipped: false, filePath, tailoredId, atsScore: ats.score };
}

function buildEmailBody({ job, ats }) {
  return `
RESUME ASSISTANT — TAILORED RESUME
====================================

Role:     ${job.title}
Company:  ${job.company}
${job.url ? `Job URL:  ${job.url}` : ''}

ATS MATCH SCORE: ${ats.score}/100
${ats.summary}

✅ Matched Keywords:
${(ats.matched_keywords || []).map((k) => `  • ${k}`).join('\n')}

⚠️  Missing Keywords (consider adding):
${(ats.missing_keywords || []).map((k) => `  • ${k}`).join('\n')}

====================================
Tailored resume attached as .docx
Generated by Resume Assistant
  `.trim();
}

module.exports = { processJob };
