'use strict';

const path = require('path');
const os = require('os');
const { getProfile, seenJobBefore, saveTailored, markDelivered } = require('./db');
const { tailorResume, calculateAtsScore, createJobTrace } = require('./llm');
const { renderResumeDocx } = require('./renderDocx');
const { sendResumeEmail } = require('./mailer');

async function processJob(job) {
  const alreadySeen = await seenJobBefore(job);
  if (alreadySeen) return { skipped: true };

  if (!job.jd_text || job.jd_text.trim().length < 50) {
    console.log(`· Skipping ${job.job_id} — no JD available`);
    return { skipped: true };
  }

  // One trace per job — groups tailor_resume + ats_score together
  const trace = createJobTrace(job);

  const profile = await getProfile();
  const resume = await tailorResume(profile, job, trace);
  const ats = await calculateAtsScore(resume, job, trace);

  console.log(`✓ ATS Score for ${job.company}: ${ats.score}/100`);

  const safe = (s) => String(s || 'x').replace(/[^a-z0-9]+/gi, '_');
  const fileName = `resume_${safe(job.company)}_${safe(job.title)}.docx`;
  const filePath = path.join(os.tmpdir(), fileName);
  await renderResumeDocx(resume, filePath);

  const tailoredId = await saveTailored(job.job_id, resume, filePath);

  await sendResumeEmail({
    subject: `[ATS ${ats.score}/100] ${job.title} @ ${job.company}`,
    text: buildEmailBody({ job, ats }),
    attachmentPath: filePath,
    attachmentName: fileName,
  });

  await markDelivered(tailoredId);

  // Update trace with final result
  trace.update({
    output: { ats_score: ats.score, resume_file: fileName },
  });

  return { skipped: false, filePath, tailoredId, atsScore: ats.score };
}

function buildEmailBody({ job, ats }) {
  return `
RESUME ASSISTANT — TAILORED RESUME
====================================

Role:     ${job.title}
Company:  ${job.company}
${job.url ? `Job URL:  ${job.url}` : ''}

ATS MATCH SCORE: ${ats.score}/100
${ats.summary}

✅ Matched Keywords:
${(ats.matched_keywords || []).map((k) => `  • ${k}`).join('\n')}

⚠️  Missing Keywords (consider adding):
${(ats.missing_keywords || []).map((k) => `  • ${k}`).join('\n')}

====================================
Tailored resume attached as .docx
Generated by Resume Assistant
  `.trim();
}

module.exports = { processJob };
